image: node:latest

Test:
  before_script:
  - npm install -g @angular/cli
  - npm i -D puppeteer
  - npm install
  - ng build
  stage: test
  tags:
  - ci-test
  script:
  - ng test
  except:
  - tags
