services:
    - name: docker.texta.ee/texta/texta-rest:latest
      alias: texta-rest
    - name: redis:latest
    - name: postgres:11
      alias: texta-postgres
    - name: docker.texta.ee/texta/texta-uaa:latest
      alias: texta-uaa

variables:
    DJANGO_DATABASE_ENGINE: "django.db.backends.postgresql"
    DJANGO_DATABASE_NAME: docker
    DJANGO_DATABASE_USER: docker
    DJANGO_DATABASE_PASSWORD: docker
    DJANGO_DATABASE_HOST: texta-postgres
    DJANGO_DATABASE_PORT: 5432
    POSTGRES_DATABASE: docker
    POSTGRES_USER: docker
    POSTGRES_PASSWORD: docker
    TEXTA_ES_URL: http://elastic-dev.texta.ee:9200
    TEXTA_MLP_URL: http://mlp-dev.texta.ee:5000
    TEXTA_REDIS_URL: redis://redis:6379/0
    TEXTA_API_URL: http://texta-rest
    TEXTA_USE_CSRF: "False"
    npm_config_cache: "$CI_PROJECT_DIR/.npm"
    CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"
    FF_NETWORK_PER_BUILD: 1
    # MLP
    TEXTA_LANGUAGE_CODES: et
    # UAA
    TEXTA_USE_UAA: "False"
    TEXTA_UAA_REDIRECT_URI: http://texta-rest/api/v1/uaa/callback
    TEXTA_UAA_USER: test1
    TEXTA_UAA_EMAIL: test1@test1.com
    TEXTA_UAA_PWD: test1
    TEXTA_UAA_URL: http://texta-uaa:8080/uaa
    TEXTA_UAA_FRONT_REDIRECT_URL: http://localhost:4200/oauth
    TEXTA_UAA_CLIENT_ID: login
    TEXTA_UAA_CLIENT_SECRET: loginsecret

stages:
  - unit-test
  - e2e-test
  - build

Karma:
  image: circleci/node:10-browsers
  script:
    - npm ci
    - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  stage: unit-test
  tags:
  - ci-test

Cypress:
  image: cypress/browsers:node12.16.2-chrome81-ff75
  stage: e2e-test
  tags:
    - ci-test
  before_script:
    - npm ci
    - sh wait_for_uaa.sh
  script:
    - npm run cy:verify
    - npm run cy:info
    - npm run cypress:ci
  artifacts:
    when: always
    paths:
      - cypress/videos/**/*.mp4
      - cypress/screenshots/**/*.png
    expire_in: 1 day

build:
  image: node:latest
  stage: build
  tags:
    - ci-test
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'  
    - npm install -g @angular/cli
    - npm ci
  script:
    - ng build --prod
    - mkdir release
    - tar -czvf release/texta-rest-front-latest.tar.gz dist/TEXTA
    - cp release/texta-rest-front-latest.tar.gz release/texta-rest-front-${CI_COMMIT_TAG}.tar.gz
    - ssh-add <(echo "$STAGING_PRIVATE_KEY")
    - ssh texta-docs@web.texta.ee "mkdir -p /opt/packages/texta-rest-front"
    - scp -r release/* texta-docs@web.texta.ee:/opt/packages/texta-rest-front
  only:
    - tags
