image: node:latest

#services:
#  - name: docker.texta.ee/texta/texta-rest:latest
#    alias: texta-rest

#variables:
#  TEXTA_ES_URL: http://172.17.0.1:9200

Test:
  before_script:
  - npm install -g @angular/cli
  - npm install
  - ng build
  stage: test
  tags:
  - ci-test
  variables:
    apiUrl: http://texta-rest:8000
  script:
  - ng test
  except:
  - tags
