image: node:latest

#services:
#  - name: docker.texta.ee/texta/texta-rest:latest
#    alias: texta-rest

Test:
  before_script:
  - npm install -g @angular/cli@7.3.8
  stage: test
  tags:
  - ci-test
  variables:
    TEXTA_ES_URL: http://172.17.0.1:9200
  script:
  - ng test
  except:
  - tags
