image: node:latest

services:
  - name: docker.texta.ee/texta/texta-rest:latest
    alias: texta-rest

Test:
  before_script:
  - npm install -g @angular/cli@7.3.8
  - ng build
  stage: test
  tags:
  - ci-test
  variables:
    apiUrl: http://texta-rest:8000
  script:
  - ng test
  except:
  - tags
