image: node:latest

#services:
#  - name: docker.texta.ee/texta/texta-rest:latest
#    alias: texta-rest

Test:
  before_script:
  - npm install -g @angular/cli
  - npm i -D puppeteer
  - npm install
  - ng build
  stage: test
  tags:
  - ci-test
  variables:
    CHROME_BIN: 
    apiUrl: http://texta-rest:8000
  script:
  - ng test
  except:
  - tags
